version: "2"
services:
    cache:
        container_name: ocs-redis
        image: redis

    php-fpm:
        image: sawyerlin/docker-fpm-app
        container_name: ocs-cgi
        depends_on:
            - cache
        volumes:
            - ./:/var/www
        ports:
            - 9000:9000

    web:
        container_name: ocs
        build: apache
        volumes:
            - ./ocs-freeboxv5:/var/www
        depends_on:
            - php-fpm
        environment:
            - VIRTUALHOST=htdocs
            - PORT=9000
            - PHP=php-fpm
            - APP=ocs-freeboxv5
networks:
    default:
        external:
            name: ocs-freeboxv5
